### PR TITLE
Fix usage of stream

### PR DESCRIPTION
**Pull request by CrafterKolyan**

### CODE REVIEW

**Comment by choldgraf** [comment]
What's the benefit of this? `stream=True` triggers the download once you access the content of the response, but we do this immediately anyway, no?

**Comment by CrafterKolyan** [comment]
Without `stream=True` you are actually getting the whole file in call of `requests.get`. Your progressbar shouldn't work correct then. Compare these two codes:
```
import requests
from tqdm.auto import tqdm

url = "https://github.com/salesforce/WikiSQL/raw/master/data.tar.bz2"
path = "data.tar.bz2"
chunk_size = 8192

resp = requests.get(url)

with open(path, "wb") as ff:
    for chunk in tqdm(resp.iter_content(chunk_size=chunk_size), unit="B", unit_scale=True):
        if chunk:  # filter out keep-alive new chunks
            ff.write(chunk)
```
and
```
import requests
from tqdm.auto import tqdm

url = "https://github.com/salesforce/WikiSQL/raw/master/data.tar.bz2"
path = "data.tar.bz2"
chunk_size = 8192

resp = requests.get(url, stream=True)

with open(path, "wb") as ff:
    for chunk in tqdm(resp.iter_content(chunk_size=chunk_size), unit="B", unit_scale=True):
        if chunk:  # filter out keep-alive new chunks
            ff.write(chunk)
```

First one works very long and even doesn't show a progress bar. Second one shows the progress bar and the actual download speed because you don't get the whole file at once but get it with chunks.

This may be useful: https://kite.com/python/docs/requests.Response.iter_content 
> When stream=True is set on the request, this avoids reading the content at once into memory for large responses.

**Comment by CrafterKolyan** [comment]
Also I am not sure but this may fix #23

**Comment by choldgraf** [comment]
ah good catch 👍 thanks for the improvement

**Pull request merged**
